images:
  - name: mysql
    image: mysql
    tag: latest

  - name: nginx
    image: nginx
    tag: latest

  - name: redis
    image: redis
    tag: latest

  - name: mihomo
    image: metacubex/mihomo
    tag: latest

  - name: nacos-server
    image: nacos/nacos-server
    tag: v3.1.1-slim

  - name: odoo
    image: odoo
    tag: latest

  - name: postgres
    image: postgres
    tag: 18

  - name: frpc
    image: jalena/frpc
    tag: latest

  - name: frps
    image: jalena/frps
    tag: latest
