images:
  - name: mysql
    image: mysql
    tag: lts

  - name: nginx
    image: nginx
    tag: stable-alpine

  - name: redis
    image: redis
    tag: latest

  - name: nacos-server
    image: nacos/nacos-server
    tag: v3.2.1-slim

  - name: odoo
    image: odoo
    tag: latest

  - name: postgres
    image: postgres
    tag: 18
