name: Sync Multiple Images to CNB

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  sync-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # 即使其中一个失败，也继续执行其他的同步任务
      matrix:
        include:
          - source: metacubex/mihomo:latest
            target: docker.cnb.cool/youvigo/base/mihomo:latest

          - source: mysql:lts
            target: docker.cnb.cool/youvigo/base/mysql:lts

          - source: nginx:stable-alpine-perl
            target: docker.cnb.cool/youvigo/base/nginx:stable-alpine-perl

          - source: redis:7.4-alpine
            target: docker.cnb.cool/youvigo/base/redis:7.4-alpine

          - source: nacos/nacos-server:v3.1.1-slim
            target: docker.cnb.cool/youvigo/base/nacos-server:v3.1.1-slim

    steps:
      - name: Sync Image using Skopeo
        run: |
          echo "🚀 开始同步: ${{ matrix.source }} -> ${{ matrix.target }}"

          # GitHub 官方的 ubuntu-latest 已经预装了 skopeo
          # 使用 docker:// 前缀告诉 skopeo 这是一个标准的容器镜像仓库
          skopeo copy --all \
            --dest-creds="cnb:${{ secrets.CNB_TOKEN }}" \
            docker://${{ matrix.source }} \
            docker://${{ matrix.target }}

          echo "✅ 同步完成!"
